### PR TITLE
add example client with connection error handling

### PR DESCRIPTION
**Pull request by msimerson**

### CODE REVIEW

**Comment by pfmooney** [comment]
What are your thoughts on updating the example to use some of the new 'setup' event stuff?
It was intended to make client initialization easier. (And should be documented before 0.8 is cut)

**Comment by msimerson** [comment]
> use some of the new 'setup' event stuff

I don't know much about this. My app was throwing exceptions when it couldn't connect to the LDAP server so I blundered about until I found where to add those event handlers for connection errors.

**Comment by pfmooney** [comment]
It doesn't help that I haven't written docs for it yet.

Here's a short example of using the setup event to bind:
https://github.com/joyent/node-ufds/blob/c7aa5635871aad7a630c897be2fcf059fed2e9dd/lib/index.js#L439-L455

ldapjs will run the 'setup' handlers sequentially after establishing a TCP connection but before emitting 'connect' to the client consumer.  The idea is to simplify event handling in the face of connect/reconnect scenarios.

**Comment by msimerson** [comment]
Mmm, that does look like a much nicer interface.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.

**Pull request closed without merging**
