### PR TITLE
Add node 4,5 and 6 to the build matrix

### PR DESCRIPTION
**Pull request by robbyoconnor**
Test against Node v4,5, and 6.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Is there no webhook for Travis setup or why are the status checks not appearing? o.o

**Comment by robbyoconnor** [comment]
I set it up on my fork: https://travis-ci.org/robbyoconnor/node-ldapjs/ 

Probably something in the code...I'll have a look

**Comment by felixfbecker** [comment]
🎉 

I feel much more confident now using it.

**Comment by robbyoconnor** [comment]
Not sure why CI is failing https://travis-ci.org/mcavage/node-ldapjs/builds/160907730

**Comment by robbyoconnor** [comment]
Passed for me here: https://travis-ci.org/robbyoconnor/node-ldapjs/builds/160905783

**Comment by pfmooney** [comment]
4.x and "stable" have been added to the Travis config in 2a9ce5515d8a62d629955cbc2eb7c6aafd4df475

Thanks

**Comment by felixfbecker** [comment]
@pfmooney just a heads-up, the badge in the readme is broken

**Comment by robbyoconnor** [comment]
This.

**Comment by felixfbecker** [comment]
GitHub status checks also don't seem to run

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.

**Pull request closed without merging**
