### PR TITLE
permit Anonymous Authentication Mechanism

### LINKED ISSUE #254: no support for empty credentials
hi. a bit new to poking around with ldap, but I think I found a problem. Trying to leave credentials blank (anonymous usage)
but here:
https://github.com/mcavage/node-ldapjs/blob/master/lib/client/client.js#L468

`assert.string(credentials, 'credentials');`

but a few lines down, there is support for credentials being falsy
https://github.com/mcavage/node-ldapjs/blob/master/lib/client/client.js#L480

```
var req = new BindRequest({
    name: name || '',
    authentication: 'Simple',
    credentials: credentials || '',
    controls: controls
  });
```

So before i do a pr removing the assert, wanted to check with you.

### PR DESCRIPTION
**Pull request by msimerson**
As documented here: http://tools.ietf.org/html/rfc4513#section-5.1.1

closes #254

### CODE REVIEW

**Comment by pfmooney** [comment]
In the test, you're calling `bind` with `BIND_PW`.
Is that really what you want for a passwordless bind test?

**Comment by msimerson** [comment]
doh! I'll get right on that.

**Comment by msimerson** [comment]
test updated, with a zero length name and zero length password.

**Comment by pfmooney** [comment]
Merged in 19f2c167839fc9cfb46fdb8ee1ef5275100fd578.
Thanks

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.

**Pull request closed without merging**
